---
- hosts: localhost
  connection: local
  gather_facts: 'no'
  become: 'no'
  vars:
    colon: ':'

  pre_tasks:
    - shell: echo 'mackbook provisioning!'
  tasks:
    # tab completion for Mac OS X terminal
    - name: setup tab completion
      shell: cat './inputrc.txt' >> ~/.inputrc
      args:
        creates: ~/.inputrc

    # rust
    - name: download rust installer
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup.sh
      notify: install rust

    # oh-my-zsh
    - name: install oh-my-zsh
      shell: curl -sL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
      args:
        creates: ~/.oh-my-zsh/
      notify: install zsh-completions

    # zsh-completions
    - name: install zsh-completions
      shell: git clone https://github.com/zsh-users/zsh-completions ~/.oh-my-zsh/custom/plugins/zsh-completions
      args:
        creates: ~/.oh-my-zsh/custom/plugins/zsh-completions
      notify: setup zsh

    # install fzf configurations
    - name: install fzf configurations
      shell: /usr/local/opt/fzf/install --all --no-fish --64

    # custom fzf command
    - name: custom fzf command
      shell: cp ./dotfzf.commands.zsh ~/.fzf.commands.zsh

    # replace .zshrc.local file
    - name: replace .zshrc.local file
      shell: cp ./dotzshrc.local ~/.zshrc.local

    # solarized dircolor for ls
    - name: install solarized dircolor
      get_url:
        url: https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.256dark
        dest: ~/.dircolors-solarized

    # tmux
    - name: replace .tmux.conf
      shell: cp ./dottmux.conf ~/.tmux.conf

    # Ricty
    - name: install xquartz for Ricty
      homebrew_cask: name=xquartz
    - name: install fontforge for Ricty
      homebrew: name=fontforge
    - name: install Ricty
      homebrew: name=ricty
    - name: copy ttf files
      shell: cp -f $(brew --cellar ricty)/*/share/fonts/Ricty*.ttf ~/Library/Fonts/
      args:
        creates: ~/Library/Fonts/Ricty-Bold.ttf
      notify: run fc-cache

    # terraform
    - name: install zsh-completion for terraform
      get_url:
        url: https://raw.githubusercontent.com/dtan4/terraforming/master/contrib/zsh-completion/_terraforming
        dest: /usr/local/share/zsh/site-functions/_terraforming

    # sops
    - name: install sops
      shell: go get -u go.mozilla.org/sops/cmd/sops

  handlers:
    - name: run fc-cache
      shell: fc-cache -vf
    - name: setup zsh
      script: ./setup_zsh.sh
    - name: install rust
      shell: sh /tmp/rustup.sh -y
