---
- hosts: localhost
  connection: local
  gather_facts: 'no'
  become: 'no'
  vars:
    colon: ':'

  pre_tasks:
    - shell: echo 'mackbook provisioning!'
  tasks:
    # rust
    - name: download rust installer
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup.sh
      notify: install rust

    # Ricty
    - name: install xquartz for Ricty
      homebrew_cask: name=xquartz
    - name: install fontforge for Ricty
      homebrew: name=fontforge
    - name: install Ricty
      homebrew: name=ricty
    - name: copy ttf files
      shell: cp -f $(brew --cellar ricty)/*/share/fonts/Ricty*.ttf ~/Library/Fonts/
      args:
        creates: ~/Library/Fonts/Ricty-Bold.ttf
      notify: run fc-cache

    # terraform
    - name: install zsh-completion for terraform
      get_url:
        url: https://raw.githubusercontent.com/dtan4/terraforming/master/contrib/zsh-completion/_terraforming
        dest: /usr/local/share/zsh/site-functions/_terraforming

    # sops
    - name: install sops
      shell: go get -u go.mozilla.org/sops/cmd/sops

  handlers:
    - name: run fc-cache
      shell: fc-cache -vf
    - name: install rust
      shell: sh /tmp/rustup.sh -y
