---
- name: install google-cloud-sdk (gcloud, kubectl, etc...)
  homebrew_cask:
    name: google-cloud-sdk
    state: present
    update_homebrew: yes

- name: update gcloud components
  shell: gcloud components update
