---
- name: List Installed Vagrant Plugins
  shell: "vagrant plugin list | awk '{ print $1 }'"
  changed_when: false
  register: vagrant_plugin_list

- name: Install Vagrant Plugins
  shell: "vagrant plugin install {{item}}"
  loop:
    - sahara
    - vagrant-cachier
    - vagrant-exec
    - vagrant-proxyconf
    - vagrant-vbguest
    - vagrant-omnibus
    - vagrant-rsync-back
  when: item not in vagrant_plugin_list.stdout_lines
