---
- name: install pip packages
  pip:
    name: "{{packages}}"
    executable: pip3
  vars:
    packages:
      - virtualenv
      - protobuf

- name: setup .direnvrc
  shell: cp ./dotfiles/.direnvrc $HOME/.direnvrc
