---
- name: Install anyenv
  shell: git clone https://github.com/riywo/anyenv $HOME/.anyenv
  args:
    creates: $HOME/.anyenv

- name: Install pyenv-virtualenv
  shell: git clone https://github.com/yyuu/pyenv-virtualenv $HOME/.anyenv/envs/pyenv/plugins/pyenv-virtualenv
  args:
    creates: $HOME/.anyenv/envs/pyenv/plugins/pyenv-virtualenv
