---
- name: Install dein
  shell: curl -sL https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh | sh -s $HOME/.config/nvim/dein
  args:
    creates: $HOME/.config/nvim/dein

- name: install pynvim replated pip packages
  pip:
    executable: "/usr/local/bin/pip3"
    name: "{{packages}}"
    extra_args: --user
  vars:
    packages:
      - pynvim
      - mypy
      - yamllint
      - black
      - flake8

- name: Update .config/nvim/init.vim
  shell: cp dotfiles/nvim/init.vim $HOME/.config/nvim/init.vim

# Ref. https://github.com/ambv/black/blob/master/.flake8
- name: set up flake8 config
  shell: cp ./dotfiles/.flake8 $HOME/.flake8
